name: lint

on: # Rebuild any PRs and main branch changes
  push:
    branches:
      - main
  pull_request_target:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 🧹 lint
        uses: avto-dev/markdown-lint@v1
        with:
          config: '.markdownlint.json'
          args: '**/*.md .github/**/*.md'
